# обновлены монтирования, чтобы включить новые папки
services:
  db:
    image: postgres:15
    container_name: barkane_db
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
    networks:
      - barkane_net

  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: barkane_php
    restart: always
    env_file:
      - .env
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db
    networks:
      - barkane_net

  nginx:
    image: nginx:alpine
    container_name: barkane_nginx
    restart: always
    ports:
      - "8099:80"
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - barkane_net

volumes:
  postgres_data:

networks:
  barkane_net:
